namespace: armbian
name: armbian
version: 1.0.3
readme: README.md
authors:
  - Sam Doran <sdoran@redhat.com>
  - Lane Jennion <lane@lane-fu.com>

description: Modules for Armbian.

license:
  - GPL-2.0-or-later

tags:
  - development
  - system
  - debian
  - armbian

dependencies: {}

repository: http://github.com/armbian/ansible-collection-armbian
documentation: http://github.com/armbian/ansible-collection-armbian/README.md
homepage: http://github.com/armbian/ansible-collection-armbian
issues: http://github.com/armbian/ansible-collection-armbian/issues

build_ignore: []
