namespace: samdoran
name: armbian
version: 1.0.0
readme: README.md
authors:
  - Sam Doran <sdoran@redhat.com>

description: Roles and custom content for manangig macOS

license:
  - GPL-2.0-or-later

tags:
  - development
  - system
  - debian
  - armbian

dependencies: {}

repository: http://github.com/samdoran/ansible-collection-armbian
documentation: http://github.com/samdoran/ansible-collection-armbian/README.md
homepage: http://github.com/samdoran/ansible-collection-armbian
issues: http://github.com/samdoran/ansible-collection-armbian/issues

build_ignore: []
